import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import Link from "next/link";
import './globals.css';
import "tailwindcss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Adalicious",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="p-4 flex flex-row items-center bg-(--firstColor) shadow-md">
          <Link href="./">
            <h1 className="text-2xl font-bold hover:text-(--fourthColor)">Adalicious 🥦</h1>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
