import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Adalicious",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={styles.adaliciousTitle}>Adalicious 🥦</header>
        <Link href="./">Retour à l'accueil</Link>
        {children}
      </body>
    </html>
  );
}
